10 FIB = [N,M] ~> IF (M==UNDEFINED) THEN FIB(N, MRET({1, 1})) ELSE IF (LEN(MJOIN(M)) >= N) THEN HEAD(MJOIN(M)) ELSE FIB(N, M >>= ([XS] ~> MRET((XS(0) + XS(1)) ! XS)))
20 FOR K = 1 TO 10
30 PRINT FIB(K);" ";
40 NEXT
