10 DEFUN F(STR,XS)=IF (XS==UNDEFINED) THEN F(STR,{}) ELSE IF (LEN(STR)==0) THEN XS ELSE F(RIGHT(STR,LEN(STR)-1),IF (LEN(XS)==0) THEN XS ~ {LEFT(STR,1),1} ELSE IF (XS(LEN(XS)-1,0)><LEFT(STR,1)) THEN XS ~ {LEFT(STR,1),1} ELSE INIT(XS) ~ {LEFT(STR,1),1+XS(LEN(XS)-1,1)})
100 PAIRS=F("aaaabbbccaxyzzy")
110 PRINT PAIRS
